const Types = {
  getters: {},
  mutations: {
    LOGOUT: 'LOGOUT',
    SAVE_TOKEN: 'SAVE_TOKEN',
    FETCH_USER: 'FETCH_USER',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
    UPDATE_USER: 'UPDATE_USER'
  },

  actions: {
    ACTION_LOGOUT: 'ACTION_LOGOUT',
    ACTION_SAVE_TOKEN: 'ACTION_SAVE_TOKEN',
    ACTION_FETCH_USER: 'ACTION_FETCH_USER',
    ACTION_UPDATE_USER: 'ACTION_UPDATE_USER'
  }
}
export default Types
